name: ML in prodaction hw1

# Controls when the workflow will run
on: 
  push:
    branches: [ hw-1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name:
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: installation
        working-directory: ./gryumova_ML_in_production
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        working-directory: ./gryumova_ML_in_production
        run: |
          flake8 . --count --select=E9,F63,F7,F821 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        working-directory: ./gryumova_ML_in_production
        run: |
          pytest